### ISSUE TITLE
Instruction to build and run tests, benchmark

### ISSUE THREAD

**Issue by breznak** [intel/parallelstl#31]
Hello, 

I want to test this repo as I plan to use c++17 TS Parallel in my library. 

My system is on g++-9, Ubuntu, which should be a supported configuration. 

When I clone this repo, cmake runs fine and finds TBB 2019 (which I installed). 
Running `make` then produces nothing at all. 

I think cmake targe `all` should compile all code required, or am I doing something wrong? 
Thanks for any help

**Comment by AlexVeprev** [comment]
Hi @breznak,
Current Parallel STL version in this repo doesn't support test execution through CMake. In order to run tests you can do the following:
```
cd build
make test compiler=gcc stdver=c++17
```
But as you use g++-9 with C++17 you will get many compilation errors running these commands due to conflict with libstdc++.

It may make sense to you to use parallel algorithms from libstdc++ (for configurations which don't have parallel algorithms in standard library you can use Parallel STL from this repo).

https://gcc.gnu.org/gcc-9/changes.html:

> **Runtime Library (libstdc++)**
> - Improved support for C++17, including:
>   - ...
>   - **Parallel algorithms and `<execution>` (requires Thread Building Blocks 2018 or newer).**
>   - ...

**Comment by bigpieit** [comment]
hi @breznak 
can you explain more detail about how you compiled tbb and pstl from source? thx!

**Comment by breznak** [comment]
> how you compiled tbb and pstl from source?

I didn't. 
G++-9 from PPA, and TBB (in desired version) pinned from ubuntu 19.10's repos.

**Comment by tbbdev** [comment]
Current version of Parallel STL supports test execution through CMake: target `check-pstl` runs all the found tests. Feel free to reopen the issue if it is still actual.
